# Generated by Django 4.2.15 on 2024-08-13 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day_7_app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AddField(
            model_name='author',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(2)]),
        ),
    ]
