# Generated by Django 4.2.15 on 2024-08-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day_7_app_1', '0003_author_full_name_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
