# Generated by Django 4.2.15 on 2024-08-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day_7_app_1', '0004_alter_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='test',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
