# Generated by Django 4.2.15 on 2024-08-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Day_7_app_1', '0005_author_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='test',
        ),
    ]
