# Generated by Django 4.2.15 on 2024-08-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Day_7_app_1', '0007_alter_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='full_name',
        ),
    ]
