# Generated by Django 4.2.15 on 2024-08-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day_7_app_1', '0008_remove_author_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
