# Generated by Django 4.2.15 on 2024-08-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day_7_app_1', '0011_alter_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='images',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
