# Generated by Django 4.2.15 on 2024-08-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(unique=True)),
                ('services', models.CharField(choices=[('cybersecurity', 'cybersecurity'), ('clousaecurity', 'clousaecurity'), ('pentesting', 'pentesting'), ('hacking', 'hacking')], default='hacking', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=20)),
                ('certification', models.TextField()),
                ('full_name', models.CharField(editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default="don't have the description ", null=True)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('starts', models.FloatField()),
                ('slug', models.SlugField(default='', editable=False)),
            ],
        ),
    ]
