# Generated by Django 4.2.15 on 2024-08-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_author_comment_post_tags_delete_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_link',
        ),
        migrations.AddField(
            model_name='post',
            name='file_fields',
            field=models.FileField(null=True, upload_to='imagesss'),
        ),
    ]
