# Generated by Django 3.2.19 on 2024-09-05 08:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_table',
            name='quandity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
