# Generated by Django 3.2.19 on 2024-09-05 09:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_table', '0002_cart_table_quandity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_table',
            name='quandity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=1), blank=True, default=list, size=None),
        ),
    ]
