# Generated by Django 3.2.19 on 2024-09-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_table', '0003_alter_cart_table_quandity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_table',
            old_name='user_id',
            new_name='user',
        ),
    ]
