# Generated by Django 3.2.19 on 2024-09-03 18:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_Table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_Name', models.CharField(max_length=100)),
                ('P_description', models.TextField(max_length=100)),
                ('P_Price', models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100000)])),
                ('P_Stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('P_Brand', models.CharField(max_length=100)),
                ('P_image', models.ImageField(upload_to='Product_Image')),
                ('P_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_Table.category_table')),
            ],
        ),
    ]
