# Generated by Django 3.2.19 on 2024-09-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Table', '0002_auto_20240907_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='P_Price',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='product_table',
            name='P_Stock',
            field=models.CharField(max_length=5),
        ),
    ]
