# Generated by Django 4.2.15 on 2024-08-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pics', models.ImageField(upload_to='posts')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default="don't have the description ", null=True)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('likes', models.FloatField()),
                ('slug', models.SlugField(default='', editable=False)),
            ],
        ),
    ]
