# Generated by Django 3.2.19 on 2024-09-05 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product_Table', '0001_initial'),
        ('Shipping_Table', '0002_alter_shipping_table_shipping_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_date', models.DateField(auto_now=True)),
                ('Total_amount', models.FloatField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Table.product_table')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipping_Table.shipping_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
