# Generated by Django 3.2.19 on 2024-09-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shipping_Table', '0002_alter_shipping_table_shipping_status'),
        ('Order_Table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shipping_Table.shipping_table'),
        ),
    ]
