# Generated by Django 3.2.19 on 2024-09-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='profiles/default_profile.jpg', upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
