# <<<<<<< HEAD
# # Generated by Django 3.2.19 on 2024-09-04 13:01
# =======
# # Generated by Django 3.2.19 on 2024-09-05 07:13
# >>>>>>> 51fd64acc2d5c0431dfe1874877c6c3dffd0ddd7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Table', '0002_auto_20240904_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='profiles/default_profile.jpg', null=True, upload_to='profiles/'),
        ),
    ]
