# Generated by Django 3.2.19 on 2024-09-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20)),
                ('message', models.TextField()),
                ('rating', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
