# Generated by Django 4.2.15 on 2024-08-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagesclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='test_image')),
            ],
        ),
    ]
