# Generated by Django 3.2.19 on 2024-09-07 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='P_Price',
            field=models.CharField(max_length=5, validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product_table',
            name='P_Stock',
            field=models.CharField(max_length=5, validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(1)]),
        ),
    ]
