# Generated by Django 3.2.19 on 2024-09-07 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Table', '0003_auto_20240907_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='P_Price',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='product_table',
            name='P_Stock',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(20)]),
        ),
    ]
