# Generated by Django 3.2.19 on 2024-09-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipping_Table', '0002_alter_shipping_table_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_table',
            name='shipping_status',
            field=models.CharField(max_length=10),
        ),
    ]
